### ISSUE TITLE
When will the problem of excessive disk usage be resolved? Now the disk has reached 2T

### ISSUE THREAD

**Issue by heipacker** [klaytn/klaytn#1131]
**Is your request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeongkyun-oh** [comment]
Dear @heipacker,

Thanks for leaving the issue here.
Actually, we have been trying to find a solution for disk usage. We already developed a function to reduce disk usage named `State DB Migration`. Briefly speaking, we pinpoint a specific block and copy the all states to new database (and new data will be written on the newly created db). After that, we removed old database. It was 2 years ago and we doing this periodically. 

Check this article: [Korean](https://medium.com/klaytn/klaytn-state-migration-%EB%B8%94%EB%A1%9D%EC%B2%B4%EC%9D%B8%EC%9D%98-storage%EB%A5%BC-%EC%A4%84%EC%97%AC%EB%B3%B4%EC%9E%90-8472287b3d0c) / [English](https://medium.com/klaytn/klaytn-state-migration-an-efficient-way-to-reduce-blockchain-data-6615a3b36523)

Well, we know the disk usage is getting higher despite of state db migration (The article says archiving node took about 2TB, but now it takes 2TB after db migration). So, we definitely need another option for this issue such as state trie pruning, light client, etc. We cannot say exactly what we will do and when it will be resolved. But, we will be trying hard to resolve excessive disk usage. Furthermore, if you have any suggestion or any idea, please share with us. Let us know what you are struggling with and what you can suggest to resolve this.
