### ISSUE TITLE
Ethereum API compatiblity tests with Ethereum tools 

### ISSUE THREAD

**Issue by sirano11** [klaytn/klaytn#1192]
To support compatibility with Ethereum, we need to test with Ethereum tools. 
This issue dependent with https://github.com/klaytn/klaytn/issues/1128 task.

The tools we test
  - Library 
    - web3.js v1.7.0
    - ethers.js v5.5.4
  - Framework
    - truffle v5.5.3
    - hardhat v2.8.4
  - Open source DApp
    - TBD

Library
- Test whether the newly added eth namespace APIs are accepted  response without formatting error.
  - [x] web3.js
  - [x] ethers
- Use the contract wrapping object to check whether the contract is deployed/executed.
  - [x] web3.js
  - [x] ethers

Framework
- Test whether the distribution and execution of the sample contract are successful.
  - [x] truffle
  - [x] hardhat
- Test hardfork feature.
  - [x] ethers

Open source DApp
- [x] When migrating the open source dapp source to klaytn as it is, test whether it is successfully migrated.

**Comment by sirano11** [comment]
### Library test result 
**Test whether the newly added eth namespace APIs are accepted response without formatting error.**
  - In case Ethers.js, the provider.send() function can call all Klaytn functions. However, since it returns a js object and doesn't do any formatting checks, I exclude it.

### Block related API : Pass

Block related API | web3.js | ethers.js
-- | -- | --
eth_getblockByHash | web3.eth.getBlock | provider.getBlockWithTransaction
eth_getblockByNumber | web3.eth.getBlock | provider.getBlockWithTransaction
eth_getUncleByBlockHashAndIndex | web3.eth.getUncle | N/A
eth_getUncleByBlockNumberAndIndex | web3.eth.getUncle | N/A
eth_getHeaderByNumber | N/A | N/A
eth_getHeaderByHash | N/A | N/A


### Transaction related API - pass

transaction related function | web3.js | ethers.js
-- | -- | --
eth_getTransactionByHash | web3.eth.getTransaction | provider.getTransaction
eth_gettransactionbyblockhashandindex | web3.eth.getTransactionFromBlock | N/A
eth_gettransactionbyblocknumberandindex | web3.eth.getTransactionFromBlock | N/A
eth_signTransaction | web3.eth.signTransaction | N/A
eth_sendTransaction | web3.eth.sendTransaction | signer.sendTransaction
eth_fillTransaction | N/A | N/A
eth_sendRawTransaction | web3.eth.sendSignedTransaction | N/A
eth_pendingTransaction | N/A | N/A

### Receipt API - pass
Receipt API | web3.js | ethers.js
-- | -- | --
eth_getTransactionReceipt | web3.eth.getTransactionReceipt | provider.waitForTransaction

### Others API - pass
Others API | web3.js | ethers.js
-- | -- | --
eth_feeHistory | web3.eth.getFeeHistory | N/A
eth_coinbase | web3.eth.getCoinbase | N/A
eth_minning | web3.eth.isMining | N/A
eth_hashrate | web3.eth.getHashrate | N/A
eth_getwork | web3.eth.getWork | N/A
eth_submitwork | web3.eth.submitWork | N/A
eth_submitHashrate | N/A | N/A
eth_getunclecountbyblockhash | N/A | N/A
eth_getunclecountbyblocknumber | N/A | N/A
eth_sign | web3.eth.sign | signer.signMessage
eth_call | web3.eth.call | provider.call
eth_estimateGas | web3.eth.estimateGas | provider.estimateGas
eth_newBlockFilter | N/A | N/A
eth_newfilter | N/A | N/A
eth_newblockfilter | N/A | N/A
eth_newPendingTransactionFilter | N/A | N/A
eth_newPendingTransactions | N/A | N/A
eth_uninstallfilter | N/A | N/A
eth_getfilterchanges | N/A | N/A
eth_getfilterlogs | N/A | N/A
eth_getLogs | N/A | provider.getLogs
eth_syncing | web3.eth.isSyncing | N/A
eth_chainId | web3.eth.getChainId | provider.getChainId
eth_account | web3.eth.getAccounts | jsonRpcProvider.listAccounts
eth_blockNumber | web3.eth.getBlockNumber | provider.getBlockNumber
eth_getBalance | web3.eth.getBalance | provider.getBalance
eth_getCode | web3.eth.getCode | provider.getCode
eth_getStorageAt | web3.eth.getStorageAt | provider.getStorageAt
getTransactionCount | web3.eth.getTransactionCount | provider.getTransactionCount
eth_getBlockTransactionCountByHash | web3.eth.getBlockTransactionCount | N/A
eth_getBlockTransactionCountByNumber | web3.eth.getBlockTransactionCount | N/A
eth_maxPriorityFeePerGas | N/A | provider.getFeeData
eth_gasPrice | web3.getGasPrice | provider.getGasPrice
eth_getProof | web3.eth.getProof | N/A
eth_createAccessList | web3.eth.createAccessList | N/A

**Comment by sirano11** [comment]
## Truffle Test 

#### Testing version
- Klaytn version : v1.8.0-rc.2
- truffle : v5.5.3
- truffle/hdwallet-provider : v2.0.3

#### Test Result 
- Checkout the `Metacoin` box in Truffle, and Test it.
  - Deploy to Klaytn : pass
  - Test to execute contract with Klaytn : pass

#### Consideration
- To interact contract with Truffle, It needs to be set `gasPrice` to 25 ston in `truffle-config.js`
- Currently it need to set a gas in `truffle-config.js` or in each transaction object.
```
networks: {
   testKlaytn: {
    provider: () =>
      new HDWalletProvider({
        providerOrUrl: "en url",
        privateKeys: [],
        shareNonce: true,
      }),
      gas: 50000000,
      gasPrice: 25000000000,
      network_id: "*"
   }
  },
```

**Comment by ian0371** [comment]
### Hardhat test

I tested a smart contract using hardhat, and had to adjust a few settings to send txs of the new type.
- `gas` field must be set (as mentioned above)
- Specify `maxFeePerGas` and `maxPriorityFeePerGas` every tx whose values must match the gas price (due to https://github.com/klaytn/klaytn/blob/dev/blockchain/tx_pool.go#L663)

```
// hardhat.config.js
// ----- snipped -----
task("deploy", "Deploys GovernanceContract", async () => {
  Gov = await ethers.getContractFactory("GovernanceContract");
  gov = await Gov.deploy({
    maxFeePerGas: 25000000000,
    maxPriorityFeePerGas: 25000000000,
  });
  console.log("Deployed address:", gov.address);
});

// ----- snipped -----
module.exports = {
  networks: {
    cypress: {
      url: "http://127.0.0.1:8551",
      chainId: 10000,
      gas: 50000000,
      accounts: {
        mnemonic: "test test test test test test test test test test test junk",
        initialIndex: 0,
      },
    },
    hardhat: {
        // ----- snipped -----
    },
  },
};
```

**Comment by blukat29** [comment]
## Snapshot.org test

#### Testing version

- Klaytn: v1.8.0 testnet
- snapshot.org: latest

#### Test result

- Run a dApp called [snapshot.org](https://snapshot.org/) by [snapshot-labs](https://github.com/snapshot-labs).
- Ported version is at https://github.com/blukat29/snapshot-klaytn.
- This app uses `StaticJsonRpcProvider` from ethers.js. ([source](https://github.com/blukat29/snapshot-klaytn/blob/master/snapshot.js/src/utils/provider.ts)) ([network config](https://github.com/blukat29/snapshot-klaytn/blob/master/snapshot.js/src/networks.json#L722))
- This app would invoke a contract using the provider. I guess it uses `eth_call`? ([source](https://github.com/blukat29/snapshot-klaytn/blob/master/snapshot.js/src/utils.ts#L44))
- This app wants to know token balances of voters at given block number (called 'snapshot block') ([source](https://github.com/blukat29/snapshot-klaytn/blob/master/snapshot-strategies/src/strategies/erc20-balance-of/index.ts#L20))
- Creating proposal and voting works correctly.

#### Considerations

- Klaytn [Public ENs](https://docs.klaytnapi.com/tutorial/public-node-api/public-en) only allow queries at every 128 blocks. 
- As a workaround, I've patched the frontend to round up the 'snapshot block' to multiple of 128. ([patch](https://github.com/blukat29/snapshot-klaytn/commit/7982a8b8c07f28c6fefd7b35866d912e8c70409e))
- In general, service developers who want to query historical data
  - Should round the block number to multiple of 128
    ```js
	block -= (block % 128)
	```
  - Otherwise use an archive endpoint like https://api-geth-archive.ankr.com/.
