### ISSUE TITLE
Sanity check for v1.8.0

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1222]
- [ ] qa-tool @yoomee1313 (3/12~)

**Comment by yoomee1313** [comment]
## rpc
* test_eth_getHeaderByNumber_RPC_error_wrong_value_param2
  * This test fails because eth_getHeaderByNumber and klay_getHeaderByNumber's behavior is different.

```
> klay.blockNumber
36999
> eth.getHeaderByNumber("0xffffffff")
null
> klay.getHeaderByNumber("0xffffffff")
Error: the header does not exist (block number: 4294967295)
    at web3.js:3278:20
    at web3.js:6805:15
    at web3.js:5216:36
    at <anonymous>:1:1
```
* test_eth_getBlockByHash_RPC_error_wrong_value_param
  * This test fails because eth_getBlockByHash and klay_getBlockByHash's behavior is different.

e.g.
```
ubuntu@ip-10-117-2-254:~$ curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"klay_getBlockByHash","params":["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", true],"id":1}' http://localhost:8551
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"the block does not exist (block hash: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)"}}

ubuntu@ip-10-117-2-254:~$ curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", true],"id":1}' http://localhost:8551
{"jsonrpc":"2.0","id":1,"result":null}
```
* other tests are passed.
## ws
* test_eth_getHeaderByNumber_WS_error_wrong_value_param2
  * same as rpc
* test_eth_getBlockByHash_WS_error_wrong_value_param
  * same as rpc
* other tests are passed.

## js
* `CAVERJS-UNIT-ETC-400: signTransaction should send a signed transaction using an account in the node.` failed. It's in etcTest.
* `intSOLTest` cannot be run. I think this error is caused by https://github.com/klaytn/caver-js/pull/606. I'll figure it out later, and upload the `intSOLTest` result.
* other tests are passed.

## java
pass

## governance
pass

## reward
pass

## rolling update
pass

cc. @jimni1222 @aeharvlee @aidan-kwon

**Comment by aidan-kwon** [comment]
About HTTP/WS API failtures,
Returning `nil` instead of an error is what we expected for `eth_getHeaderByNumber`. 
It was changed to get compatibility with Ethereum API in https://github.com/klaytn/klaytn/pull/1228.

**Comment by aeharvlee** [comment]
@yoomee1313 
Thanks for reporting. I fixed that test cases at https://github.com/Krustuniverse-Klaytn-Group/rpc-tester/pull/43 .

**Comment by jimni1222** [comment]
@yoomee1313 I posted a [PR](https://github.com/klaytn/caver-js/pull/622) to fix TC to send essential gasPrice field.

**Comment by yoomee1313** [comment]
There's no critical error discovered, so test is ended successfully.
