### ISSUE TITLE
Question about governance function on hard-forked chain by KIP71

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1429]
As the txPool's gas price is determined by `calcBaseFee()` call in KIP71 hardfork, I think the API [updateUnitPrice](https://github.com/klaytn/klaytn/blob/dynamicGasPrice/governance/handler.go#L112) should be removed. 

cc. @kjeom, @blukat29

**Comment by blukat29** [comment]
@hyunsooda It should not be removed. The code will be used by
- chains with KIP71Hardfork = nil 
- chains with KIP71Hardfork block number, but before the block number.

I think it's txpool's responsibility to ignore the `SetGasPrice()` call after hardfork block number.

- https://github.com/klaytn/klaytn/blob/v1.8.4/blockchain/tx_pool.go#L490:
```go
func (pool *TxPool) SetGasPrice(price *big.Int) {
    if pool.chainconfig.IsKIP71ForkEnabled(pool.currentBlockNumber) {
        return
    }
    // existing code..
}
```

**Comment by hyunsooda** [comment]
My question was whether to remove `updateUnitPrice()`, not the `SetGasPrice()`. Or maybe I'm missing your point?

**Comment by kjeom** [comment]
@hyunsooda updateUnitPrice() is a callback function when updating governance parameter so it has been used before hardfork.

**Comment by hyunsooda** [comment]
Yes. It must not be removed for now. I was considering this functionality should be removed once the hardfork is done.

**Comment by blukat29** [comment]
> My question was whether to remove `updateUnitPrice()`, not the `SetGasPrice()`. Or maybe I'm missing your point?

@hyunsooda I meant to keep both `updateUnitPrice()` and `SetGasPrice()`. We can support the use case where KIP71 fork is not enabled forever. For instance, a hypothetical company may want to run a v1.9.0 service chain without KIP71 fork for the fixed gas price experience.

Is there a reason why `updateUnitPrice` must be removed?

**Comment by hyunsooda** [comment]
@blukat29, 

Thanks for the good explanation. The fixed gas price seems still preserved if the GCs vote the `UpperBoundBaseFee` and `LowerBoundBaseFee` values equally. Thus, the guide to teaching for the case seems better instead of holding the ambiguous function.

**Comment by blukat29** [comment]
@hyunsooda Good point. I see that `UpperBoundBaseFee == LowerBoundBaseFee` is equivalent to setting `UnitPrice`.

## When can we remove it

But before remove an existing feature, we need to carefully consider about already running blockchains.

- **Case A. Start chain without KIP71. HF not planned or before HF.** 
  - i.e. `HFBlock = nil` or `HFBlock > head`
  - updateUnitPrice (hence SetGasPrice) **needed**.
    - Upon `unitprice` governance vote, we must reflect the change to the Txpool.
- **Case B. Start chain without KIP71. After HF.**
  - i.e. `HFBlock <= head`
  - updateUnitPrice (hence SetGasPrice) **not needed**.
    - `unitprice` is irrelevant since HF.
    - Fortunately, no problem replaying historic blocks. updateUnitPrice only affects Txpool, not block processing.
- **Case C. Start chain with KIP71**
  - i.e. `HFBlock = 0`
  - updateUnitPrice (hence SetGasPrice) **not needed**.
    - `unitprice` is irrelevant

From this short analysis, I conclude that we can remove `updateUnitPrice()` after all chains are enabled KIP71.

Please note that updateUnitPrice is rather special case. Most features cannot be removed even after hardfork because blockchiain nodes must keep the ability to process pre-hardfork blocks. UnitPrice feature must be kept as well since we need to validate historic transactions with varying UnitPrice.

## How to make all chains enable KIP71

I anticipate Klayn Cypress and Baobab to proceed to Case B in the near future (Case A->B)
So it should be okay to remove the function in these networks.

For service chain operators,
- Existing chains should enable HF before we remove the function (Case A->B).
  Or they can just use old binaries (Case A).
- New chains should enable KIP71 from the genesis (Case C).
  Or they can just use old binaries (Case A).

To remove the updateUnitPrice function, I think we can start by announcing the deprecation of the UnitPrice feature.
After chain operators are sufficiently informed and has taken necessary actions, then we can remove it.

**Comment by kjeom** [comment]
@blukat29 Thank you for considering various cases.

I think certain service chain operators may want to have a `unitprice` policy from the start.
In that case, It's better to activate `unitprice` policy with disabled kip71 because It is more intuitive.

I considered the case, `UpperBoundBaseFee == LowerBoundBaseFee` for following.
- An operator have enabled kip71
- Some time later, want to set a fixed `base fee` for some reason.

Nevertheless, if you think it's better to remove `updateUnitPrice`, we should offer detailed instructions for setting kip71 default parameters by homi. As I know, it doesn't seem to support `governance settings` for service chain by homi yet.

**Comment by blukat29** [comment]
@kjeom I agree that simply using UnitPrice is much more intuitive.

@hyunsooda Why do you think we should remove the function? We can remove it, but at the cost of sufficient communication with node operators and developers. So I want to hear the reason behind deprecating a feature. To make code cleaner? because UnitPrice vs. BaseFee is confusing to operators/users?

**Comment by hyunsooda** [comment]
@blukat29,  The expected schedule for removal `updateUnitprice` is surely subsequent on hardfork. Please refer my [preceding comment](https://github.com/klaytn/klaytn/issues/1429#issuecomment-1152132193).

I thought it was better to remove this function because it creates confusion for platform developers by important policy change and the outdated functionality for legacy policy (collision) is still there.

@kjeom,  Seems not to matter. It can be achieved with a manual update. Furthermore, the awareness of those new KIP71-related governance parameters should be eventually supported on `homi` anyway (because of hardfork). 

Consquentely in short:
- If those functionalities (voting item with handler) are held, it can be said as another shortcut control of `unitPrice` to GCs. If that functionality is removed, the direct control is not given to any GCs, but indirect control is still possible. I'm not sure about the tradeoff between communication cost for the guide and tidy implementation.

**Comment by aidan-kwon** [comment]
@hyunsooda It seems that there are another conversation in another channel. Please, close this issue if you have enough answer.
