### ISSUE TITLE
question about the purpose of --block-generation-time-limit flag 

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1562]
First, let me briefly tell you what I understood about the `--block-generation-time-limit` flag.
When handling the ChainHeadEvent of the consensus completed block by the Istanbul BFT,
it seems to be to control when the run time of the evm is exceeded in the process of running txs.(https://github.com/klaytn/klaytn/blob/fe873d5e875cb03558fb51267e453132b5f7e724/work/worker.go#L669)
If there is anything wrong, please feel free to point it out.

So, I have some questions and some little concerns after seeing this flag.

1. Unlike general limit control mechanisms such as gas, vm execution time will different between nodes. 
So carefully, I think it seems some non-deterministic point.
if there are some CN nodes that lacks hardware performance, it may fail to run tx depending on the setting.
Then, because the state will different, those nodes will not be able to keep up the consensus. (After that, even if the consensus completed block  by other nodes is received as a gossip, I think  timeout will occur again while executing the transaction again.)
could you please explain this concern?(could you please explain why CN need to apply these limit?)

2. By what criteria is the default value of 250ms set? I wonder what criteria I will set in the appropriate value.
What I'm vaguely guessing right now is that...
a. mesure the average of bad delay time of one consensus round in the current validators council network configuration.
b. subtract from targeted block generation time.
 
3. Regarding this code, I found an releated comment '[TODO-Klaytn-Issue615](https://github.com/klaytn/klaytn/blob/fe873d5e875cb03558fb51267e453132b5f7e724/blockchain/vm/interpreter.go#L346)'. However, the issue was not found in github. could you please explain this issue?

Once again, please feel free to point out any wrong in what I understand. Thank you.

**Comment by jiseongnoh** [comment]
Thank you for raising this issue.

1) As you mentioned, VM execution time can differ between the consensus nodes according to their hardware specification. One point I would like to say is that the timeout only applies to the block proposer, which is 250 milliseconds by default. The other nodes, i.e. validators, do not use the timeout counter when validating the consensus.

Slow validators may take more time to validate and insert the block into their database, but they will not suffer from the timeout event. 

2) The 250-millisecond timeout is set so that blocks can be generated in one second. 

Block generation time is calculated by (block proposing time + block propagation and consensus time + block validation and insertion time). According to our empirical analysis, it can take up to 500 milliseconds for the nodes to reach consensus. 

Block validation and insertion time is nearly equal to (or slightly greater than) block proposing time. As a result a timeout of 250 milliseconds for block proposing can be considered reasonable.

 Changing block proposing time affects block validation and insertion time, which also have an impact on block generation time.

**Comment by brew0722** [comment]
Thank you for your answer kindly! @jiseongnoh 

First, I'll pick up the wrong part.
I mistook worker as a procedure to execute the consensus completed block. It's a mistake that I guessed would be similar to other BFT consensus implementation as tendermint.

Now, I understand that validators execution first before the worker sends the proposal(So this is definitely not an consensus completed block.).
However, I still feel like all validators still execute that(with `--block-generation-time-limit`). because `CommitNewWork` seems to be running every validators even if it's not a proposer. but as a result, the `core.handleRequest` broadcasts `preprepare` only if it is the current round's proposer.


Let me ask you a few more questions. I'm taking your a lot of time by asking questions without fully understanding the Istanbul BFT. I'm sorry.

1. If the proposer of round0 cannot submit the proposal for above reason, It seems will be timeout by `roundChangeTimer` and to move on to new round1. Am I right to understand?
2. The block that the validator executed by above, if not the proposer, It's definitely not used as a proposal. but it seems to be saved as a `pendingRequest`. And, `pendingRequest` seems to be used as a block proposed by the next round proposer if consensus fails in the current round.
Then, If the next proposers has continued to time out on evm due to a very large block, What kind of situation is there?

**Comment by jiseongnoh** [comment]
1) yes, roundChangeTimer is set by `newRoundChangeTimer()` , and round change occurs on timeout.

2) yes, non-proposers also mine a block and the block is stored in c.current.pendingRequest, and  the next round’ proposer sends its pendingRequest block when round change happens. By sending this pendingRequest block, it can reduce block mining time when round change happens.

I quite did not understand what you mentioned in the last sentence, “proposer times out on evm… what kind of situation is there”. 

As you mentioned, the next round’s proposer also executes up to 250 milliseconds to mine a block, which is the same as the current round’s proposer. When the current round is expired due to timeout, the next round’s proposer sends the stored block. 

If there are too many transaction requests to execute, the next round proposer will execute the remaining requests.

**Comment by brew0722** [comment]
The question in 2-2 was, in fact, what if all the validators also failed with a `--block-generation-time-limit` flag by a large block and couldn't make all the proposals for the next rounds that I was wondering.

But I misunderstood the big premise earlier. The question left in 2-1 was to ask if the proposal could not be broadcasted if the flag failed, and the round change timer occurred. However there was an error in my think.

Even if it fails with the `block-generation-time-limit` flag, only one tx that was last running is interrupted, and a proposal is created as a result of running the previous tx.(That's why the `block-generation-time-limit` flag doesn't cause round change.) 
I misunderstood that would `cancel` all of the evm state that was preparing without deep analyzing the `evm.cancel` `abort` code flow. So, I misunderstood that it will not be submit a proposal.

It helped me a lot to understand. Thank you!
