### ISSUE TITLE
Question about how to upgrade from 1.8.4 to 1.9.0(magma) in the service chain

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1574]
I found that magma hardfork is applied in 1.9.0 (`MagmaCompatibleBlock`).
Cypress/Baobobab seems hard-coded the block number in default genesis.

I think that if the service chain in operation needs the feature of 1.9.0, we will have to respond in the same way with a hard fork.
However, I could not find a way to specify `MagmaCompatibleBlock` in the service chain in operation.

1. Could you tell me how to upgrade in a running service chain?
2. I tried `kscn` `dumpGenesis` / `dumpConfig` command in the process of finding a way. However, this command seems to be output only on a cypress/baobab basis. Is there any command that provides the same command in the service chain?

**Comment by yoomee1313** [comment]
> Could you tell me how to upgrade in a running service chain?

Fundamentally, hardfork of the service-chain is same as the hardfork of the private network. Also, we're preparing the guide which describes the private-network/service-chain hardfork to clarify the steps. If you want to know in advance, you can refer `Scheduling Hard Forks` contents located at ethereum guide. https://geth.ethereum.org/docs/interface/private-network 

But i recommend waiting until guide came out because magma hardfork contains some special features(such as dynamic gas fee) so i think more specific guide is needed.

> I tried kscn dumpGenesis / dumpConfig command in the process of finding a way. However, this command seems to be output only on a cypress/baobab basis. Is there any command that provides the same command in the service chain?

klaytn code does not provide dumping private network genesis. Same as service chain.

**Comment by brew0722** [comment]
1. thank you! It seems that the `init` command is also used for upgrade, not only initialization first. I will wait for the guide as your recommended.

2. Okay, I don't need it because I can see it directly even if no command is given. I just asked because the command is provided by kscn.

**Comment by yoomee1313** [comment]
@brew0722 Thanks for your patience. We will add a link at this issue comment as soon as the guide is published!

**Comment by 2dvorak** [comment]
@brew0722 Sorry for the late update, but the guide is now available. Please refer to [Klaytn Docs](https://docs.klaytn.foundation/node/service-chain/references/upgrade-and-hard-fork).

**Comment by brew0722** [comment]
@2dvorak  Awesome, guide content LGTM. thks for your sharing.
