### ISSUE TITLE
Question about the compatibility of the service chain being bridged

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1582]
Hi. I have another question. Thank you for always answering kindly.

First, let me tell you why I started investigating Protocol Versions.
With this mainnet 1.9.0 magma upgrade, I was curious about the compatibility of the service chain being bridged.

I see that the `SCProtocolVersion` increased from 1 to 2 by KIP71.
Since the bridge runs together in the scn process, I think the the service chain node version needs to be raised as well.
Depending on the some feature or situation added at the time, I am worried that it may be difficult to upgrade the service chain in operation according to the mainnet schedule.

I have some questions.

1. Is the coupling must be needed between the service chain version and the main chain version by the bridge?
2. If there are rules that can keep backward compatibility of the service chain, When the mainnet version comes release, where should I check for  backward compatibility of the service chain?
3. Do you have a plan to separate the bridge process from the scn for compatibility or stability?
4. Besides `SCProtocolVersion`, is there anything else that affects compatibility between the mainnet and the service chain?

**Comment by hyunsooda** [comment]
Hi @brew0722,

1. Yes. Two bridge nodes must have the same protocol version.
2. Release note and medium post would be appropriate places to check out the release changes. We will pay attention to announcing the change of SC through Release note and medium. The best is to directly check the source code you already know. 
3. The SCN implementation is a bridge service module (called `service` in the source-code level) on top of the CN implementation. As I, a developer of SC package, I didn't have inconvenience experience with compatibility management because it's quite simple, just increase the protocol number. Could you elaborate on what `stability` means from which context?
4. The contract version is also important to check out (You don't need to consider its number for now because we did never increase its number until now). The contract versions must be matched between two bridge contracts as well as compatible with `SCN` node's protocol version number. For the latter, we will pay attention to note its change.

Thanks for the good question.

**Comment by brew0722** [comment]
Thank you for your answer.

2. If possible, I think it would be good to refer to the compatibility if it is organized in the klaytn docs.
3.  Let me list a few reasons why I thought about stability of 3.
a. I think the bridge function doesn't have to work on the validator node. Wouldn't a level equivalent to fullnode be enough?
There is a slight worry that the validator needs to be terminated due to the bridge feature update.
b. For the same reason, if the node process panics due to bridge feature, the consensus is affected.
But there's something wrong with my thinking...
Looking at it again, the bridge (including anchoring) seems to operate as sen or spn also in addition to scn. If this is correct, I think you can ignore the question about 3.

answers helped me a lot, Thanks again!

**Comment by hyunsooda** [comment]
2. Good suggestion. We will consider putting the changes to docs as well. 

3-a. Bridge implementation does not have any interaction with CN implementation.

3-b. Eventually, the `SCN` is one program with a CN implementation and bridge implementation. Thus, a panic in CN or bridge forces to terminate a process. The panic never should happen on both sides, and it seems to depend on reliable implementation by developers. 

3-c. Don't worry. it's easier to detect incompatible binary issues. Suppose you run two binaries with different protocol version numbers and try to establish the bridge between them. In that case, a bridge is not established by the error of a different protocol version number. For the contract, we don't have a guard for its error for now because we didn't consider the big change of the contract for now. But, it will be developed later with big change (bridge v2 implementation is ongoing implemented)

**Comment by brew0722** [comment]
Oh, I think my expression was lacking. The reason I asked you about 3-c was that I wanted to be able to use the bridge between 1.8.4(servicechain) and 1.9.0(klaytn mainnet). 

Anyway, Any major updates coming to the bridge? Then, it would be better to wait for an update than to understand now.
I'm looking forward to it. If I have any questions about v2, I'll ask you again.

**Comment by hyunsooda** [comment]
@brew0722, I'm sorry I misread it and now got your concerns for 3-c.

As the `SCN` is a network program, it has some of the defined requests and corresponding handlers. That's why the protocol version must be matched to have expected behaviors. An assumption that no use of the new changes of requests and handlers are not guaranteed WLOG.

**Comment by brew0722** [comment]
Okay. Then, when upgrading the mainnet, I will remember that the service chain may also need to be upgraded.
Thanks for your time.
