### ISSUE TITLE
ken is leaking memory - baobab

### ISSUE THREAD

**Issue by tmeinlschmidt** [klaytn/klaytn#1603]
**Describe the bug**
Even after upgrading to 1.9.0 and 1.9.1 we spot that our ken instances reloading every 3 to 4 days because of OOM. From our monitoring memory usage increases around 500kB-1MB/1minute and it's not freed.

**How to reproduce**
run ken with parameters provided

**Expected behavior**
stable memory usage

**Environment (please complete the following information)**
- `Klaytn v1.9.1+8664bc8831`
- using binary from `https://packages.klaytn.net/klaytn/1.9.1/ken-baobab-1.9.1-0-linux-amd64.tar.gz` 

```
ken --baobab --port 30035 --srvtype fast http --syncmode full --gcmode archive --datadir /data/baobab \
--rpc --rpcaddr 0.0.0.0 --rpcapi admin,debug,klay,miner,net,personal,rpc,txpool,web3 --rpccorsdomain * \
--rpcport 8551 --rpcvhosts * --maxconnections 10 --ws --wsaddr 0.0.0.0 \
--wsapi debug,klay,net,personal,rpc,txpool,web3 --wsorigins * --wsport 8552 --state.tries-in-memory 50
```

**Comment by yoomee1313** [comment]
How was the memory size? Were you syncing? And, how many RPC requests per second? 

We recommend using a machine with 60GB memory or more when syncing. Without syncing, 30GB memory is okay.

Also, we found that with the RPC load such as getBlock, a memory leak was found. The fix is https://github.com/klaytn/klaytn/pull/1650. If you experience similar problem, try this.

**Comment by aidan-kwon** [comment]
Hope to https://github.com/klaytn/klaytn/pull/1650 mitigate your issue. If you still have the same problem with the latest version of Klaytn, please let us know.
