### ISSUE TITLE
Ambiguous chainConfig API name

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1615]
**Is your request related to a problem? Please describe.**
The `governance_chainConfig` API name seems ambiguous because it prints only the initial chain configuration, not the currently activated values.

**Describe the solution you'd like**
How about renaming it more appropriately?

**Describe alternatives you've considered**
Such as `initialChainConfig`, etc. 

**Additional context**

cc. @blukat29

**Comment by blukat29** [comment]
I agree that the API name is misleading.
It's quite an old issue arisen since the development of the dynamic gas fee. (https://github.com/klaytn/klaytn/issues/1391)

In my opinion, in the long term the ChainConfig should be one of
- the initial (genesis) values
- the latest values
- only immutable values (e.g. ChainID, *CompatibleBlock). Mutable fields are removed away.

I haven't decided which way should we go. We'll need experiments and discussions among the devs.

In the short term, however, we could
- add `governance_initialChainConfig` API
- promote using `governance_initialChainConfig` in the Klaytn docs, Forum Q&A, Discord, etc.

Will the short-term fix work for you? @hyunsooda

**Comment by hyunsooda** [comment]
Both are fine for me. Can I close it? or would you close after you make a change?
