### ISSUE TITLE
Do you have unpruned chaindata snapshot?

### ISSUE THREAD

**Issue by XieSen** [klaytn/klaytn#1833]
Freely describe your questions or issues here.

I want to deploy a archive endpoint node with fully history state dating back to the genesis block. I need to run trace over every block

Currently I can only find the pruned chaindata from https://packages.klaytn.net/cypress/chaindata/. 

Except syncing data from the earliest, do you have any suggestions?

Thank you

**Comment by aidan-kwon** [comment]
The size of the archive node chaindata is very large, so we are providing AWS AMIs instead of a download link. 
You can find public AMIs for Klaytn chaindata in the AWS Seoul region.
Search `cypress-clean-archive-en` at the community AMI tab on the AMI catalog page. Then, we will find a few AMIs named as `cypress-clean-archive-en-YYYYMMDD`.

**Comment by aidan-kwon** [comment]
I am closing this issue. If you have further questions, please make another issue.
