### ISSUE TITLE
[Staking] Question about an interval of staking balance

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1836]
The staking update interval appears to have been miscalculated. Here's an example to illustrate the issue, using a value of 10 (rather than the actual value of 86400) for the staking update interval:

Suppose a validator candidate stakes an amount greater than the current minimum at block 13. Ideally, this candidate should be promoted at block 20, but the promotion does not take effect until block 30. 

I have two possible explanations for this behavior:
Firstly, it may be an implementation error. (I have checked and found that no changes have been made to the implementation since the first commit.)
Secondly, it is possible that the author intended to ensure that at least one interval must pass before a promotion occurs.

This is kindly to make sure which is correct. Can anyone ensure which one would be correct?

**Comment by jeongkyun-oh** [comment]
@hyunsooda As far as I know, it is designed as you described. Staking information is used an interval after when it is created. According to your example, a CN stakes more than minimum at 13, the related staking information will be created at block 20. The created one will be affected to the range 30-39. This was intentional by the designer, however I am not sure about why.

**Comment by hyunsooda** [comment]
Thank you. Let me close this
