### ISSUE TITLE
Supporting path based state scheme for full nodes

### ISSUE THREAD

**Issue by kaliubuntu0206** [klaytn/klaytn#2021]
It would be great if the node supports path based state scheme which reduces significant disk space for full nodes ( not for archive nodes though )

Related: https://github.com/ethereum/go-ethereum/issues/25390

**Comment by blukat29** [comment]
@kaliubuntu0206 Thanks for the suggestion. However, I don't think we'll implement the path-based DB anytime soon. 

Instead, Klaytn has taken another approach to reduce disk spaces for full nodes. It's the Live Pruning feature introduced since v1.11.0 (Aug 2023). The Live Pruning prunes hash-based DB without downtime (online). We started developing the state pruning feature last year, so we went the other way from [geth](https://blog.ethereum.org/2023/09/12/geth-v1-13-0).

If you are a node operator, you can use it now:
- https://medium.com/klaytn/strong-efficient-management-of-blockchain-data-capacity-with-statedb-live-pruning-strong-6aaa09b05f91
- https://docs.klaytn.foundation/content/klaytn/design/storage/live-pruning

Also I expect that from v1.12.0, Live Pruning can be switched on/off on the existing DB. (https://github.com/klaytn/klaytn/pull/2004)
