### ISSUE TITLE
Result of `klay_estimateComputationCost`

### ISSUE THREAD

**Issue by jiOnederfull** [klaytn/klaytn#2081]
**Is your request related to a problem? Please describe.**
I set `--opcode-computation-cost-limit=200000000` then `klay_estimateComputationCost` is changed from `100000028` to `200000235`. I'm confused because it feels like klay_estimateComputationCost changes based on the opcode-computation-cost-limit setting.

**Describe the solution you'd like**
It would be better if klay_estimateComputationCost returned the actual value regardless of the opcode-computation-cost-limit or indicated if the computation exceeded the allowable limit.

**Comment by hyunsooda** [comment]
Hi @jiOnederfull, Thanks for the issue posting.

I tend to favor the current behavior. Say I have a huge tx and want to test where it fits in which a specific range of computation cost allowed.

Try1. The tx failed at default computation cost (CC) `100000000`, and `klay_estimateComputationCost` returned `>100000000`
Try2. The tx failed at the modified CC `200000000` and `klay_estimateComputationCost` returned `>200000000`
Try3. The tx success at the modified CC `300000000` and `klay_estimateComputationCost` returned `>=200000000 x <=300000000`. 

If a developer gets the same value at Try2, he/she may think that this feature does not work. Please put additional input if there's another point of view you think. Thank you.

**Comment by jiOnederfull** [comment]
Hi @hyunsooda, thanks for your reply.

So I believe that `klay_estimateComputationCost` should calculate and return the accurate value regardless of the `--opcode-computation-cost-limit`.

Let's assume the actual `klay_estimateComputationCost` is 210000000.

If we'd like to know this value, we would have to try up to try3 at the moment. Since, as far as I know, the current behavior of `klay_estimateComputationCost` is to stop the computation immediately and return the value if it exceeds the `--opcode-computation-cost-limit`. (So it will return 20000000+a(very small value).)

In that case, we would need to try all attempts you mentioned to obtain the accurate value.

If `klay_estimateComputationCost` returns the accurate value regardless of the `--opcode-computation-cost-limit`, we wouldn't need to attempt multiple tries.

**Comment by hyunsooda** [comment]
Ah got it what you've been discouraged. In that case, setting `--opcode-computation-cost-limit=x`, where `x ~= infinite` would resolve it. Doesn'it?

For your last concern,
> ++ However, if someone try to test a very large CC, it could potentially cause network disruption. In such cases, I think it would be better to return a message indicating that the computation is inaccurate and that it exceeded the --opcode-computation-cost-limit along with the value.

It would not be harm because no public endpoint will turn this feature and it also breaks the consensus values such as `gasUsed`.

**Comment by aidan-kwon** [comment]
Thank you @jiOnederfull and @hyunsooda for suggesting good opinions. 

I empathize with the issue @jiOnederfull raised. The return of `klay_estimateComputationCost` is not intuitive when the call reaches the computation cost limit. 

@jiOnederfull has suggested two options for `klay_estimateComputationCost`. And, I prefer the second option.
1. returning the actual value regardless of the opcode-computation-cost-limit 
It could be a good solution, but I am afraid of a security issue. The API call is executed with a huge amount of gas limit not to be stopped by the gas limit. If a node allows the execution of infinite computation costs with a huge gas limit, it can exhaust the resources of a node. Since `klay` namespace is allowed to 3rd parties in public nodes or services, this issue's impact can be expanded to a DoS issue of services. 

2. indicating if the computation exceeded the allowable limit.
This is a good idea. It's behavior is similar to `klay_estimateGas`. The API also returns `gas required exceeds allowance (%d)` message when the call uses more than the upper cap of the gas limit. We can also consider returning an error with `reached the opcode computation cost limit, [the computation cost limit]` for `klay_estimateComputationCost`. 

@hyunsooda How do you think about the second option? It seems that you mostly reviewed her first option.

**Comment by hyunsooda** [comment]
Agreed. For the PR's initial suggestion, there's a [workaround](https://github.com/klaytn/klaytn/issues/2081#issuecomment-1869954499) and we just leave it as it is, right?

**Comment by aidan-kwon** [comment]
> Agreed. For the PR's initial suggestion, there's a [workaround](https://github.com/klaytn/klaytn/issues/2081#issuecomment-1869954499) and we just leave it as it is, right?

@hyunsooda I think so. As I mentioned, returning a used computation cost without the limit is too heavy. Returning an error noticing out-of-computation cost allowance would be enough to users

**Comment by hyunsooda** [comment]
Uploaded a PR at https://github.com/klaytn/klaytn/pull/2082. PTAL.

**Comment by blukat29** [comment]
@jiOnederfull As of v1.12.1, the `klay_estimateComputationCost` is unlimited by ComputationCostLimit (https://github.com/klaytn/klaytn/pull/2086). You may estimate your transaction as if there was no limit, unless it hits the gas cap or a timeout.

The rationale was that (1) there has to be a way to estimate computation cost for dApp development (2) we can cut heavy loads using `rpc.gascap` and `rpc.evmtimeout` flags.

Note that `--opcode-computation-cost-limit` is discouraged because it interferes with block processing.
