### ISSUE TITLE
Running a full node and sync'ing

### ISSUE THREAD

**Issue by calebcall** [klaytn/klaytn#2192]
If I don't download a snapshot and start the sync on a full node, it starts from block 0. Will a full node start to prune at some point or is that something I have to manually do to prevent it from keeping the entire chain?

**Comment by blukat29** [comment]
Full nodes at its default configuration will store world states once every 128 blocks.

To prune historic blocks as the block advances, specify the following flag when running the `ken`. In this case, the world states are stored once every 128 blocks, and the states older than 48 hours will be deleted nonetheless.
```
ken --state.live-pruning
```
Note that the flag must be specified before processing any block because live-pruning DB is incompatible with non-live-pruning DB.

**Comment by blukat29** [comment]
Please continue any further inquiries on https://github.com/kaiachain/kaia/issues.
