### ISSUE TITLE
callTracer bugs

### ISSUE THREAD

**Issue by Jongsic** [klaytn/klaytn#263]
**Describe the bug**

`error:"TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'"`

```
Error: TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'
    at web3.js:3276:20
    at web3.js:6449:15
    at web3.js:5214:36
    at <anonymous>:1:1
```

**How to reproduce**

* `debug_traceBlockByNumber(8017131, {tracer: "callTracer"})` (rpc, ws, console ...etc..)
* `debug.traceTransaction('0x23cb063068bbe3e71c01717b7ab4ef9990d638eb9bf8000034934b2f1a84004f', {tracer: "callTracer"})`
* `debug.traceTransaction('0xd30db4837aef1bb685644cb3f2db4522907f7b8e8d38f2e8caf045fb9ada510a', {tracer: "callTracer"})`

**Expected behavior**

* normal callTracer Result

**Environment (please complete the following information)**

* `ken-baobab-v1.1.1-3-linux-amd64`
* `Ubuntu 16.04.5`

**Comment by Jongsic** [comment]
anybody here?

**Comment by aidan-kwon** [comment]
Thank you for the report! 
It seems that there is type confusion on block fields of Javascript tracers including "callTracer". 
We gonna investigate detail and fix the bug soon.

**Comment by aidan-kwon** [comment]
The bug was originated from two reasons.
1. You tried to use `callTracer` for `Value Transfer` type transaction.
Since the tx type doesn't execute EVM, `callTracer` cannot be executed. 
If you want to use tracers that trace VM execution, you need to trace with other tx types such as `Smart Contract Execution`, `Smart Contract Deploy`, or `Legacy`. (For more detail, see https://docs.klaytn.com/klaytn/design/transactions/basic)

2. `callTracer` didn't initialize undefined variables. 
Even though `callTracer` is executed with unsupported tx types, it should not return an error. However, some variables were not properly checked and it caused the type error you reported. I fixed the problem in https://github.com/klaytn/klaytn/pull/301.

@Jongsic Please check my PR https://github.com/klaytn/klaytn/pull/301 and give comments if you have any opinions.
